# Generated by Django 5.0.7 on 2024-07-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
